/* Generated By:JavaCC: Do not edit this line. ExampleConstants.java */
package org.javacc.tutorials.example;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ExampleConstants {

  /** End of File. */
  int EOF = 0;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"a\"",
    "\"c\"",
    "\"b\"",
  };

}
