/* Generated By:JavaCC: Do not edit this line. SemanticConstants.java */
package org.javacc.tutorials.semantic;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SemanticConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int C = 6;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"a\"",
    "\"c\"",
    "\"b\"",
    "\"d\"",
    "\"e\"",
    "\"f\"",
  };

}
