/* Generated By:JavaCC: Do not edit this line. SumParserConstants.java */
package com.github.alphahinex.javacc.demo.sum;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SumParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SUM = 5;
  /** RegularExpression Id. */
  int INTEGER = 6;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\u6c42\\u548c\"",
    "<INTEGER>",
    "\"(\"",
    "\",\"",
    "\")\"",
  };

}
